#!/usr/bin/env bash

#
# Install docker and docker-compose
#
# Author: Christian Potemski <c.potemski@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/typeExists

#
# Install docker if not already installed.
#
if typeExists "docker"; then
	p_success "docker is already installed. Continuing..."
else
	install "curl"
	curl -fsSL https://get.docker.com/ | sh
	sudo usermod -aG docker $USER

	if ! typeExists "docker"; then
		p_fail "Command 'docker' is still NOT in your path, you may need to restart your computer."

#		exit 1
	fi
fi


# Install docker-compose if not already installed.
#
if typeExists "docker-compose"; then
	p_success "docker-compose is already installed. Continuing..."
else
	curl -L https://github.com/docker/compose/releases/download/1.6.2/run.sh > ./docker-compose
	sudo mv ./docker-compose /usr/bin/docker-compose
	sudo chmod +x /usr/bin/docker-compose

	if ! typeExists "docker-compose"; then
		p_fail "Command 'docker-compose' is still NOT in your path, you may need to restart your computer."

#		exit 1
	fi
fi
