#!/usr/bin/env bash

#
# Installs the storm ssh-manager binary.
#
# Author: Christian Potemski <c.potemski@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/typeExists

#
# Install storm if not already installed.
#
if typeExists "storm"; then
	p_success "storm is already installed. Continuing..."
else
	p_info "Installing storm..."

	sudo pip install stormssh

	if ! typeExists "storm"; then
		p_fail "Command 'storm' is still NOT in your path, you may need to restart your shell session and re-run this command."

		exit 1
	fi
fi
