#!/usr/bin/env bash

#
# A helper function which creates the testing working directory.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"
TEST_WORKING_DIR="$DOT_DIR/test_working_dir"

beforeEach() {
	# Remove the git-history and node_modules of the test working directory.
	rm -rf $TEST_WORKING_DIR

	#
	# Create placeholders for the CLI output tests.
	#
	touch "$DOT_DIR/tests/output/help.result.txt"

	mkdir $TEST_WORKING_DIR && cd "$TEST_WORKING_DIR"
}
