#!/usr/bin/env bash

#
# Some helpers functions and variables to decorate output.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#

underline=`tput smul`
nounderline=`tput rmul`
bold=`tput bold`
normal=`tput sgr0`

p_success () {
	printf "[ \033[00;32mOK\033[0m ] $1\n"
}
p_info () {
	printf "[\033[1;36m .. \033[0m] $1\n"
}
p_user () {
	printf "\r [ \033[0;33m?\033[0m ] $1\n"
}
p_warn () {
	printf "[\033[0;33mWARN\033[0m] $1\n"
}
p_fail () {
	printf "[\033[0;31mFAIL\033[0m] $1\n"
}
