#!/usr/bin/env bash

#
# Install composer.
#
# Author: Christian Potemski <c.potemski@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/install
source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/typeExists

#symlink config
symlink "$DOT_DIR/zsh/.zshrc" "$HOME/.zshrc"

#
# Install zsh if not already installed.
#
if typeExists "zsh"; then
	p_success "zsh is already installed. Continuing..."
else
	p_info "Installing zsh..."

  install "zsh"
	install "git"
  wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh


  if ! typeExists "zsh"; then
    p_fail "Command 'zsh' is still NOT in your path, you may need to restart your shell session and re-run this command."

    exit 1
  fi

	#change default shell to zsh
	p_info "Change default shell to zsh. Please enter your sudo password."
	sudo chsh -s `which zsh`

	p_success "zsh installation successful - reboot needed"
fi
