#!/usr/bin/env bash

#
# Install composer.
#
# Author: Christian Potemski <c.potemski@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/typeExists

#
# Install npm if not already installed.
#
if typeExists "composer"; then
	p_success "composer is already installed. Continuing..."
else
	p_info "Installing composer..."

	install "php5-common libapache2-mod-php5 php5-cli" "php"

	if typeExists "php"; then
		curl -sS https://getcomposer.org/installer | php

		if ! typeExists "composer"; then
			p_fail "Command 'composer' is still NOT in your path, you may need to restart your shell session and re-run this command."

			exit 1
		fi
	else
		p_fail "PHP needs to be installed on your system to use the composer binary, please install PHP and re-run this command."

		exit 1
	fi
fi
