#!/usr/bin/env bash

#
# Installs all dependencies and optional tools.
#
# Author: Christian Potemski <c.potemski@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

for file in $DOT_DIR/{git,python,zsh,composer,npm,atom,storm,z,prm,docker}/install; do
	[ -r "$file" ] && [ -f "$file" ] && . "$file";
done;
unset file;
