#!/usr/bin/env bash

#
# Install npm
#
# Author: Christian Potemski <c.potemski@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/typeExists

#
# Install nodejs if not already installed.
#
if typeExists "node"; then
	p_success "nodejs is already installed. Continuing..."
else
	p_info "Installing nodejs..."

	VERSION="4.4.0"
	wget https://nodejs.org/dist/v$VERSION/node-v$VERSION-linux-x64.tar.xz
	tar -xf node-v$VERSION-linux-x64.tar.xz && sudo cp -R node-v$VERSION-linux-x64/* /usr/
	rm -r node-v$VERSION-linux-x64.tar.xz node-v$VERSION-linux-x64

	if ! type_exists "node"; then
		p_fail "Command 'node' is still NOT in your path, you may need to restart your shell session and re-run this command."

		exit 1
	fi

	if ! typeExists "npm"; then
		p_fail "Command 'npm' is still NOT in your path, you may need to restart your shell session and re-run this command."

		exit 1
	fi
fi

#
# Symlink the global configuration file.
#
p_info "Symlinking the global .npmrc file..."
symlink "$DOT_DIR/npm/.npmrc" "$HOME/.npmrc"

#
# Install global npm packages.
#
p_info "Installing the global npm packages..."
npm install -g grunt-cli gulp
