#!/usr/bin/env bash

#
# Install nvm, node and npm
#
# Author: Christian Potemski <c.potemski@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/typeExists

#
# Install nodejs if not already installed.
#
if typeExists "nvm"; then
	p_success "nvm is already installed. Continuing..."
else
	p_info "Installing nvm..."

	wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash

	# make nvm available
	touch ~/.bash_profile
	. ~/.nvm/nvm.sh >> ~/.bash_profile
  . ~/.bash_profile

	VERSION="4.4"
	nvm install $VERSION
	nvm use $VERSION

	if ! typeExists "node"; then
		p_fail "Command 'node' is still NOT in your path, you may need to restart your shell session and re-run this command."

		exit 1
	fi

	if ! typeExists "npm"; then
		p_fail "Command 'npm' is still NOT in your path, you may need to restart your shell session and re-run this command."

		exit 1
	fi

	#
	# Symlink the global configuration file.
	#
	p_info "Symlinking the global .npmrc file..."
	symlink "$DOT_DIR/npm/.npmrc" "$HOME/.npmrc"

	#
	# Install global npm packages.
	#
	p_info "Installing the global npm packages..."
	sudo npm install -g grunt-cli gulp ngrok supercat

fi
